name: PLMechanics
main: ru.prisonlife.plmechanics.Main
version: 1.0
author: rntsdkv

commands:
  trade:
    description: Trade with players!
    permission: plmechanics.trade
    usage: /trade <player>
  tradeaccept:
    description: Accept the trade
    permission: plmechanics.trade.accept
    usage: /tradeaccept true/false