name: PLMechanics
main: ru.prisonlife.plmechanics.Main
version: 1.0
author: rntsdkv

commands:
  trade:
    description: Trade with players!
    permission: plmechanics.trade
    usage: /trade <player>
  tradeaccept:
    description: Accept the trade
    permission: plmechanics.trade.accept
    usage: /tradeaccept
  tradedecline:
    description: Decline the trade
    permission: plmechanics.trade.decline
    usage: /tradedecline
  s:
    description: Shout message in 40 blocks
    permission: plmechanics.messages.s
    usage: /s <message>
  w:
    description: Whisper message in 1 block
    permission: plmechanics.messages.w
    usage: /w <message>
  i:
    description: Send action in 20 blocks
    permission: plmechanics.messages.i
    usage: /i <message>
  do:
    description: Send result in 20 blocks
    permission: plmechanics.messages.do
    usage: /do <message>