name: PLMechanics
main: ru.prisonlife.plmechanics.Main
version: 1.0
author: rntsdkv

commands:
  trade:
    description: Trade with players!
    permission: plmechanics.trade
    usage: /trade <player>